variables:
  clippy_toolchain: 1.36.0
  minimum_toolchain: 1.36.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/resources
      endpoint: ctz

jobs:
- template: az-pipeline/unstable/clippy.yml@templates
  parameters:
    rustup_toolchain: ${{ variables.clippy_toolchain }}
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
    - template: admin/pipelines/bench.yml
- job: MacOS
  pool:
    vmImage: macOS-10.13
  steps:
    - template: admin/pipelines/rustup.yml
    - template: admin/pipelines/cargo-steps.yml
    - template: admin/pipelines/bench.yml
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
      minimum:
        rustup_toolchain: ${{ variables.minimum_toolchain }}
  steps:
    - template: admin/pipelines/rustup.yml
      parameters:
        rustup_toolchain: $(rustup_toolchain)
    - template: admin/pipelines/cargo-steps.yml
    - template: admin/pipelines/bench.yml
    - template: admin/pipelines/bogo.yml

# Coverage build. Requires linux, and both nightly
# and stable rust toolchains
- job: Coverage
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: admin/pipelines/rustup.yml
      parameters:
        rustup_toolchain: nightly
    - template: admin/pipelines/coverage.yml

# Check that the minimum versions specified in Cargo.toml
# do in fact build.
- job: MinimalVersions
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: admin/pipelines/rustup.yml
      parameters:
        rustup_toolchain: nightly
    - template: admin/pipelines/min-versions.yml
