language: rust
group: edge
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      rust: stable
    - os: linux
      dist: trusty
      sudo: required
      rust: nightly
      env: COVERAGE=1
    - os: osx
      rust: stable
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --upgrade pip ; fi
  - if [[ "$COVERAGE" == "1" ]]; then admin/build-lcov ; fi
  - if [[ "$COVERAGE" == "1" ]]; then gem install coveralls-lcov ; fi
  - if [[ "$COVERAGE" == "1" ]]; then rustup install stable ; fi
  - if [[ "$COVERAGE" == "1" ]]; then sudo apt-get install libclang-common-3.8-dev llvm-3.8-dev ; fi
script:
  - cargo build
  - RUST_BACKTRACE=1 cargo test
  - RUST_BACKTRACE=1 cargo test --features dangerous_configuration danger
  - cargo test --release --no-run
  - ./target/release/examples/bench
#  - ( cd trytls && ./runme )
  - ( cd bogo && ./runme )
  - cargo build --no-default-features
  - cargo test --no-default-features --no-run
  - if [[ "$COVERAGE" == "1" ]]; then ./admin/coverage          ; fi
  - if [[ "$COVERAGE" == "1" ]]; then coveralls-lcov final.info ; fi
