upper-case-acronyms-aggressive = true
check-inconsistent-struct-field-initializers = true

disallowed-types = [
  { path = "std::sync::Arc", reason = "must use Arc from sync module to support downstream forks targeting architectures without atomic ptrs" },
]
