[package]
name = "rustls-fuzzing-provider"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustls = { path = "../rustls", default-features = false, features = ["log", "std"] }

[dev-dependencies]
env_logger = { workspace = true }

[lints]
workspace = true
