# The URL the site will be built for
base_url = "https://rustls.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [{ name = "tags", render = false }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here
